### ISSUE TITLE
Python 3.12

### ISSUE THREAD

**Issue by reez** [andreasgriffin/bitcoin-safe#19]
When attempting to install bitcoin-safe with my macOS on Python 3.12, I encountered an error indicating the package requires Python <3.11, which prevents me from testing as my system is updated to Python 3.12. Here's the error message:

```
ERROR: Ignored the following versions that require a different python version: 1.0.0b0 Requires-Python <3.11,>=3.10
ERROR: No matching distribution found for bitcoin-safe
```

Would it be possible to support Python 3.12, I'm familiar-ish with a couple ways to possibly workaround this on my end, but wondering anyway. Or maybe I'm totally making some easy mistake too and it does work with 3.12-

**Comment by andreasgriffin** [comment]
Hi @reez :  Because I use [bdkpython 0.31.0](https://pypi.org/project/bdkpython/0.31.0), and there are only packages for python  <=3.10  available: https://pypi.org/project/bdkpython/0.31.0/#files

In principle there is no issue to use newer python versions, however one would need to build the bdkpython for them.  

I use https://github.com/pyenv/pyenv  to use python 3.10.  

Once I upgrade to bdkpython 1.0.0 I aim to be compatible to python >= 3.10

**Comment by reez** [comment]
> Hi @reez : I use [bdkpython 0.31.0](https://pypi.org/project/bdkpython/0.31.0), and there are only packages for python <=3.10 available: https://pypi.org/project/bdkpython/0.31.0/#files
> 
> In principle there is no issue to use newer python versions, however one would need to build bdkpython for them. You can skip `poetry` and use pip directly
> 
> ```
> poetry export --output requirements.txt    
> # build and install bdkpython manually   
> pip install -r requirements.txt  # remove bdkpython from the file.
> ```
> 
> That way you can build [bdkpython 0.31.0](https://pypi.org/project/bdkpython/0.31.0) yourself and try starting the app.
> 
> I use https://github.com/pyenv/pyenv to use python 3.10. Once I upgrade to bdkpython 1.0.0 I aim to be compatible to python >= 3.10 (but thats gonna take a (long) while)

makes sense! thanks for the response

**Comment by andreasgriffin** [comment]
Thanks to [bdkpython 0.32.0](https://pypi.org/project/bdkpython/0.32.0/) the current main branch also supports python 3.10 to  3.12.
If you'd like you can try to clone main and rerun poerty without the need for pyenv.
